services:
  - type: web
    name: bing-wo-tsukau
    # oregon: frankfurt
    plan: free
    env: go
    buildCommand: go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go
    startCommand: ./go-proxy-bingai
